name: ci-cd-fast-api
on:
  push:
    branches: main
jobs:
  upload-code-to-server:
    runs-on: ubuntu-latest
    env:
      DOMAIN: 54.163.219.154
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Add server to known hosts
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.RM_SERVER_KEY }}" > ~/.ssh/git_aws.pem
          chmod 600 ~/.ssh/git_aws.pem
          ssh-keyscan -H $DOMAIN >> ~/.ssh/known_hosts
env:
          ACTIONS_RUNNER_DEBUG: true
      - name: Run test Deployment
        run: |
          if ! ssh -v -i ~/.ssh/git_aws.pem ec2-user@$DOMAIN 'bash /home/ec2-user/deploy.sh'; then
            echo "Deployment failed"
            exit 1
          fi
        env:
          ACTIONS_RUNNER_DEBUG: true
        
      - name: Cleanup
        run: rm -f ~/.ssh/git_aws.pem
        if: always()
